global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus 自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 充电桩网关应用监控 (支持容器和本地运行)
  - job_name: 'charge-point-gateway'
    static_configs:
      - targets:
          - 'host.docker.internal:9091'  # 本地运行的gateway或容器映射的端口
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s

  # 系统指标监控
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # 容器指标监控
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Redis 指标监控
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Kafka 指标监控
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']

  # 注意：健康检查端点 /health 返回JSON格式，不是Prometheus metrics格式
  # 如需监控健康状态，建议使用blackbox exporter或在网关中添加专门的健康metrics端点
