# Charge Point Gateway - Development Environment Configuration
# 开发环境配置，覆盖默认配置中的特定项

# 应用信息
app:
  profile: "dev"

# 服务器配置 - 开发环境
server:
  host: "0.0.0.0"
  port: 8080

# Redis配置 - 本地开发环境
redis:
  addr: "localhost:6379"
  password: ""
  db: 0

# Kafka配置 - 本地开发环境
kafka:
  brokers:
    - "localhost:9092"
  consumer_group: "gateway-dev-consumer"

# 日志配置 - 开发环境详细日志
log:
  level: "debug"
  format: "console"
  output: "stdout"

# 监控配置 - 开发环境
monitoring:
  metrics_addr: ":9090"
  health_check_port: 8081
  pprof_enabled: true  # 开发环境启用性能分析

# 缓存配置 - 开发环境较小缓存
cache:
  max_size: 1000
  ttl: "30m"
  cleanup_interval: "5m"
  memory_limit_mb: 128
