# Charge Point Gateway Configuration

# 服务器配置
server:
  host: "0.0.0.0"
  port: 8080
  websocket_path: "/ocpp"
  read_timeout: "60s"
  write_timeout: "60s"
  max_connections: 100000

# Redis配置
redis:
  addr: "localhost:6379"
  password: ""
  db: 0
  pool_size: 100
  min_idle_conns: 10
  dial_timeout: "5s"
  read_timeout: "3s"
  write_timeout: "3s"

# Kafka配置
kafka:
  brokers:
    - "localhost:9092"
  upstream_topic: "ocpp-events-up"
  downstream_topic: "commands-down"
  consumer_group: "gateway-consumer"
  producer:
    retry_max: 3
    return_successes: true
    flush_frequency: "100ms"
  consumer:
    return_errors: true
    offsets_initial: "newest"

# 缓存配置
cache:
  max_size: 10000
  ttl: "1h"
  cleanup_interval: "10m"
  memory_limit_mb: 512

# 日志配置
log:
  level: "info"
  format: "console"  # console or json
  output: "stdout"   # stdout, stderr, or file path

# 监控配置
monitoring:
  metrics_port: 9090
  health_check_port: 8081
  pprof_enabled: false

# OCPP配置
ocpp:
  supported_versions:
    - "1.6"
  heartbeat_interval: "300s"
  connection_timeout: "60s"
  message_timeout: "30s"

# 安全配置
security:
  tls_enabled: false
  cert_file: ""
  key_file: ""
  client_auth: false
